// AUTO-GENERATED by the localization pipeline. Do not edit by hand.
import { starter as jaJP_starter } from "./ja-JP";
import { starter as koKR_starter } from "./ko-KR";
import { starter as zhTW_starter } from "./zh-TW";
import { starter as frFR_starter } from "./fr-FR";
import { starter as deDE_starter } from "./de-DE";
import { starter as esES_starter } from "./es-ES";
import { starter as ptBR_starter } from "./pt-BR";
import { starter as ruRU_starter } from "./ru-RU";
import { starter as itIT_starter } from "./it-IT";
import { starter as nlNL_starter } from "./nl-NL";
import { starter as trTR_starter } from "./tr-TR";
import { starter as plPL_starter } from "./pl-PL";
import { starter as viVN_starter } from "./vi-VN";
import { starter as thTH_starter } from "./th-TH";
import { starter as idID_starter } from "./id-ID";
import { starter as arEG_starter } from "./ar-EG";
import { starter as csCZ_starter } from "./cs-CZ";
import { starter as heIL_starter } from "./he-IL";
import { starter as hiIN_starter } from "./hi-IN";
import { starter as svSE_starter } from "./sv-SE";
import { starter as ukUA_starter } from "./uk-UA";
import { itMessages as jaJP_itMessages } from "./messages/ja-JP";
import { itMessages as koKR_itMessages } from "./messages/ko-KR";
import { itMessages as zhTW_itMessages } from "./messages/zh-TW";
import { itMessages as frFR_itMessages } from "./messages/fr-FR";
import { itMessages as deDE_itMessages } from "./messages/de-DE";
import { itMessages as esES_itMessages } from "./messages/es-ES";
import { itMessages as ptBR_itMessages } from "./messages/pt-BR";
import { itMessages as ruRU_itMessages } from "./messages/ru-RU";
import { itMessages as itIT_itMessages } from "./messages/it-IT";
import { itMessages as nlNL_itMessages } from "./messages/nl-NL";
import { itMessages as trTR_itMessages } from "./messages/tr-TR";
import { itMessages as plPL_itMessages } from "./messages/pl-PL";
import { itMessages as viVN_itMessages } from "./messages/vi-VN";
import { itMessages as thTH_itMessages } from "./messages/th-TH";
import { itMessages as idID_itMessages } from "./messages/id-ID";
import { itMessages as arEG_itMessages } from "./messages/ar-EG";
import { itMessages as csCZ_itMessages } from "./messages/cs-CZ";
import { itMessages as heIL_itMessages } from "./messages/he-IL";
import { itMessages as hiIN_itMessages } from "./messages/hi-IN";
import { itMessages as svSE_itMessages } from "./messages/sv-SE";
import { itMessages as ukUA_itMessages } from "./messages/uk-UA";

export const additionalTranslations: Record<string, Record<string, Record<string, string>>> = {
  "starter": {
    "ja-JP": { ...jaJP_starter, ...jaJP_itMessages },
    "ko-KR": { ...koKR_starter, ...koKR_itMessages },
    "zh-TW": { ...zhTW_starter, ...zhTW_itMessages },
    "fr-FR": { ...frFR_starter, ...frFR_itMessages },
    "de-DE": { ...deDE_starter, ...deDE_itMessages },
    "es-ES": { ...esES_starter, ...esES_itMessages },
    "pt-BR": { ...ptBR_starter, ...ptBR_itMessages },
    "ru-RU": { ...ruRU_starter, ...ruRU_itMessages },
    "it-IT": { ...itIT_starter, ...itIT_itMessages },
    "nl-NL": { ...nlNL_starter, ...nlNL_itMessages },
    "tr-TR": { ...trTR_starter, ...trTR_itMessages },
    "pl-PL": { ...plPL_starter, ...plPL_itMessages },
    "vi-VN": { ...viVN_starter, ...viVN_itMessages },
    "th-TH": { ...thTH_starter, ...thTH_itMessages },
    "id-ID": { ...idID_starter, ...idID_itMessages },
    "ar-EG": { ...arEG_starter, ...arEG_itMessages },
    "cs-CZ": { ...csCZ_starter, ...csCZ_itMessages },
    "he-IL": { ...heIL_starter, ...heIL_itMessages },
    "hi-IN": { ...hiIN_starter, ...hiIN_itMessages },
    "sv-SE": { ...svSE_starter, ...svSE_itMessages },
    "uk-UA": { ...ukUA_starter, ...ukUA_itMessages },
  },
};
